ko:
  languageCode: ko-kr
  languageDirection: ltr
  languageName: 한국어
  title: 백정렬
  weight: 1
  contentDir: content/ko
  menus: main

en:
  languageCode: en-us
  languageDirection: ltr
  languageName: English
  title: Yim's Page
  weight: 2
  contentDir: content/en
  menus: main_en
