# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Introduction
    url: who/
    weight: 10

  - name: Experience
    url: activity
    weight: 20
  - parent: Experience
    name: Educations
    url: experience/education
    weight: 21
  - parent: Experience
    name: Work
    url: experience/work
    weight: 22
  - parent: Experience
    name: Awards
    url: accomplishments
    weight: 22


  - name: Projects
    url: project/
    weight: 30

  - name: Blog
    url: blog
    weight: 40
  - parent: Blog
    name: Study
    url: blog/study
    weight: 41
  - parent: Blog
    name: Life
    url: blog/life
    weight: 42

  - name: Contact
    url: contact
    weight: 50
